version: "3.7"

services:
  es-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elk-soc-prod1\n"\
          "    dns:\n"\
          "      - elk-soc-prod1\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "      - 10.0.1.1\n"\
          "      - 10.0.0.1\n"\
          "      - 192.168.130.231\n"\
          "  - name: elk-soc-prod2\n"\
          "    dns:\n"\
          "      - elk-soc-prod2\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "      - 10.0.1.1\n"\
          "      - 10.0.0.1\n"\
          "      - 192.168.130.232\n"\
          "  - name: elk-soc-prod3\n"\
          "    dns:\n"\
          "      - elk-soc-prod3\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "      - 10.0.1.1\n"\
          "      - 10.0.0.1\n"\
          "      - 192.168.130.233\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "      - 10.0.1.1\n"\
          "      - 10.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es-cluster/es-cluster.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
