services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /home/docker/swarm-elk/certs:/usr/share/logstash/certs:ro
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=85af3232338544
      - ELASTICSEARCH_HOST_PORT=https://192.168.130.231:9250
      - LS_JAVA_OPTS=-Xmx1g -Xms1g -Dlog4j2.formatMsgNoLookups=true
    ports:
      - "5044:5044"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-s" ,"-XGET", "http://127.0.0.1:9600"]
